In [1]:
import os
import pathlib

PATH = '.cache/simulation_12_02/subgroup_9b5933c4ae9923af_all_00000000000.npz'

# https://wandb.ai/jnzhao3/LD/runs/iub62eqi?nw=nwuserjnzhao3

In [2]:
import numpy as np

In [3]:
simulation = np.load(PATH)

In [4]:
simulation['misspecification_error']

array(213.93341897)

In [5]:
simulation['r_hat']

array([0.96452009, 0.76350733, 0.58395335, 0.64251062, 0.59489333,
       0.87744423, 0.78400295, 0.78460291, 0.43465547, 0.58145721,
       0.69741318, 0.73152296, 0.91315519, 0.69557243, 0.        ,
       0.95851307, 0.90753492, 0.81792253, 0.57645572, 0.47561886,
       0.68834683, 0.85117006, 0.59519662, 0.93241723, 0.68560673,
       0.53580569, 0.91956017, 0.6759502 , 0.75318485, 0.88270774,
       0.91097873, 0.62663358, 0.94467111, 0.78707859, 0.84581252,
       0.73308711, 0.86894394, 0.54056502, 0.88174003, 0.6561258 ,
       0.70499914, 0.7936343 , 0.69744217, 0.59321183, 0.71610916,
       1.        , 0.93166725, 0.65394299, 0.62885158, 0.7574263 ,
       0.50530933, 0.7199791 , 0.86894394])

In [6]:
from datasets import load_dataset

ds = load_dataset("lmarena-ai/arena-human-preference-140k")

/home/jennifer/distortion/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
train_data = ds['train']

In [8]:
all_candidates = set(train_data['model_a']).union(set(train_data['model_b']))
all_candidate_idxs = {cand : i for i, cand in enumerate(all_candidates)}

In [9]:
all_candidate_idxs

{'amazon-nova-experimental-chat-05-14': 0,
 'qwen3-235b-a22b-no-thinking': 1,
 'claude-3-5-haiku-20241022': 2,
 'command-a-03-2025': 3,
 'claude-3-7-sonnet-20250219': 4,
 'gemini-2.5-flash-lite-preview-06-17-thinking': 5,
 'mistral-small-3.1-24b-instruct-2503': 6,
 'grok-4-0709': 7,
 'deepseek-v3-0324': 8,
 'gemma-3-27b-it': 9,
 'gemini-2.0-flash-thinking-exp-01-21': 10,
 'gemini-2.0-flash-001': 11,
 'llama-4-maverick-03-26-experimental': 12,
 'grok-3-mini-high': 13,
 'claude-3-7-sonnet-20250219-thinking-32k': 14,
 'amazon.nova-pro-v1:0': 15,
 'gemini-2.5-flash-preview-04-17': 16,
 'gemini-2.5-flash': 17,
 'gpt-4.1-2025-04-14': 18,
 'qwen3-coder-480b-a35b-instruct': 19,
 'llama-3.3-70b-instruct': 20,
 'mistral-small-2506': 21,
 'gemini-2.5-pro': 22,
 'claude-sonnet-4-20250514': 23,
 'qwq-32b': 24,
 'gemini-2.5-pro-preview-03-25': 25,
 'chatgpt-4o-latest-20250326': 26,
 'gemma-3n-e4b-it': 27,
 'hunyuan-turbos-20250416': 28,
 'claude-3-5-sonnet-20241022': 29,
 'qwen3-30b-a3b': 30,
 'llam

In [10]:
all_candidate_counts = {k : 0 for k, v in all_candidate_idxs.items()}

In [11]:
for r in train_data['model_a']:
    all_candidate_counts[r] += 1

In [12]:
for r in train_data['model_b']:
    all_candidate_counts[r] += 1

In [13]:
counts_zip = zip(all_candidate_counts.keys(), all_candidate_counts.values())
sorted_counts = sorted(counts_zip, key=lambda x: -x[1])
print(sorted_counts[:20])

[('claude-opus-4-20250514', 10092), ('gemini-2.5-flash', 9668), ('gemini-2.5-pro', 9219), ('mistral-medium-2505', 9135), ('qwen3-235b-a22b-no-thinking', 9076), ('o3-2025-04-16', 8529), ('claude-sonnet-4-20250514', 8295), ('chatgpt-4o-latest-20250326', 7650), ('gemma-3-27b-it', 7326), ('claude-3-7-sonnet-20250219-thinking-32k', 7149), ('claude-3-7-sonnet-20250219', 6852), ('command-a-03-2025', 6838), ('claude-3-5-sonnet-20241022', 6817), ('o3-mini', 6624), ('deepseek-r1-0528', 6554), ('gpt-4.1-2025-04-14', 6540), ('o4-mini-2025-04-16', 6477), ('claude-3-5-haiku-20241022', 6466), ('amazon.nova-pro-v1:0', 6383), ('claude-opus-4-20250514-thinking-16k', 6157)]


In [14]:
include_idxs = np.array([all_candidate_idxs[k[0]] for k in sorted_counts[:20]])

In [15]:
for i in include_idxs:
    print(i)

39
17
22
46
1
52
23
26
9
14
4
3
29
48
50
18
40
2
15
49


In [16]:
filtered_r_hat = simulation['r_hat'][include_idxs]
print(filtered_r_hat)

[0.6561258  0.81792253 0.59519662 0.93166725 0.76350733 0.86894394
 0.93241723 0.91956017 0.58145721 0.         0.59489333 0.64251062
 0.88270774 0.62885158 0.50530933 0.57645572 0.70499914 0.58395335
 0.95851307 0.7574263 ]


In [17]:
simulation['losers']

array([24, 42, 13, ..., 34, 23,  0], shape=(6878,))

In [42]:
filtered_idxs = np.array([i for i in range(len(simulation['losers'])) if simulation['losers'][i] in include_idxs and simulation['winners'][i] in include_idxs])

In [43]:
# filtered_winners = np.array([w for w in simulation['winners'] if w in include_idxs])
# filtered_losers = np.array([l for l in simulation['losers'] if l in include_idxs])

filtered_winners = simulation['winners'][filtered_idxs]
filtered_losers = simulation['losers'][filtered_idxs]

print('length of filtered_winners:', len(filtered_winners))
print('length of filtered_losers:', len(filtered_losers))

length of filtered_winners: 820
length of filtered_losers: 820


In [19]:
import utils_3 as ut

In [44]:
ut.misspecification_error(filtered_winners, filtered_losers, simulation['r_hat'], beta=0.5)

np.float64(36.555427491577234)

In [45]:
change_of_basis = {int(idx) : i for i, idx in enumerate(include_idxs)}
print(change_of_basis)

{39: 0, 17: 1, 22: 2, 46: 3, 1: 4, 52: 5, 23: 6, 26: 7, 9: 8, 14: 9, 4: 10, 3: 11, 29: 12, 48: 13, 50: 14, 18: 15, 40: 16, 2: 17, 15: 18, 49: 19}


In [46]:
cob_winners = np.array([change_of_basis[og] for og in filtered_winners])
cob_losers = np.array([change_of_basis[l] for l in filtered_losers])
print(cob_winners)

[ 7  7 17  1 18  7  7  2 18  5 13  6 15 17 16  0 11 10  4  4 13  1  4 11
 12  6  6 19 11 10  5 13 12 19 16  3 18  6  7 13  6  6  5 12  8  5 19 13
 15  3  6  1  4  6 10 16  3 13  1 17  9 13  6 12 11  4 15  6  3 12  1 18
 13  4 18 12  5 16 13 19  3 11 13 14  0 11 10  8  7 12  1  7 11  7 15 16
 12  1  7  6  6  1 10  1 12 18 18  2 16 10 13  7  1  6 13 18  4  6  1  7
 15 19 18 18 13  6  7  7  6  6 11  1  6  6  6  2  6  4  7  7 13  2  1 15
 11  7  4  4 11 10  7  2  1  4  7  1 10 12  4  7  4 12  6 15  4 17  8  1
 18 15  2  1  1 18 15 17  1 16  6  6 12  7  6 19  1  8 18 17 16 16 17 10
  1  4 10  6 13  2  4 11 12 11 13  1 10 11  2  6  1 10 13 13 18  4  6 15
 15  6  7 18  6 13 18  7  4  5 11 18  4 18 12 12  6  3  1  4  1 15  7  2
 18  6 12 17 11  2  6 16 10 12  0  3 15 15 16  2  6 15 12 12  6  5 12 10
  6 13  1 12  6  5  8 12  1  7  7  4 12  8 12 12 16 11  5  2 13  6  4  7
 10  2  6 16  4 12 11  9  7  7  4  2 10 10  2 12 12 13  6  2 18  1  6 14
 12 15  1 17 17  1 12  4 13  7  6  8 12  7  8 18  0

In [47]:
ut.misspecification_error(cob_winners, cob_losers, simulation['r_hat'][include_idxs], beta=0.5)

np.float64(36.555427491577234)

It's the same thing to simply exclude the irrelevant models from the winners and losers data.

In [24]:
print(simulation['r_hat'].max())
print(simulation['r_hat'].min())

1.0
0.0


## Examining the Population

In [48]:
POP_PATH = '.cache/simulation_12_02/population_9b5933c4ae9923af.npz'

population = np.load(POP_PATH)

In [49]:
dict(population).keys()

dict_keys(['pop_utilities', 'absolute_subsection_sizes', 'misspec_keys', 'misspec_values', 'included_subgroup_indices', 'avg_utils', 'true_ranking', 'borda_scores', 'ranking', 'distortion', 'k'])

In [50]:
population['pop_utilities'].shape

(20, 53)

In [51]:
avg_utils = population['pop_utilities'].sum(axis=0) / population['pop_utilities'].shape[0]
print(avg_utils)

[0.69694915 0.5744251  0.4162044  0.42444579 0.38750891 0.62311759
 0.6093603  0.6794856  0.4296384  0.47847023 0.51135387 0.53572374
 0.75246467 0.56862281 0.22136909 0.71032835 0.67986072 0.5840805
 0.35559577 0.30082141 0.51670988 0.60400845 0.4404683  0.79669648
 0.50709474 0.36905468 0.60454168 0.55805745 0.62673099 0.60237665
 0.71805909 0.53276028 0.6810587  0.59503625 0.61082149 0.64696299
 0.62627121 0.3906454  0.62464678 0.6038825  0.54159737 0.61709285
 0.43113502 0.45444065 0.55994553 0.70286374 0.75210043 0.511456
 0.48027221 0.53284327 0.46149637 0.54712579 0.62627121]


## Comparing Global Misspecification versus Subgroup Misspecification

In [52]:
ut.misspecification_error(simulation['winners'], simulation['losers'], avg_utils, beta=0.5)

np.float64(235.70374437592795)

In [53]:
ut.misspecification_error(simulation['winners'], simulation['losers'], simulation['r_hat'], beta=0.5)

np.float64(232.1240546183552)

In [54]:
ut.misspecification_error(cob_winners, cob_losers, avg_utils[include_idxs], beta=0.5)

np.float64(37.38477281416)

In [55]:
ut.misspecification_error(cob_winners, cob_losers, simulation['r_hat'][include_idxs], beta=0.5)

np.float64(36.555427491577234)

It's slightly lower in both cases, but doesn't seem that significant. Try with a different subgroup?

## Comparing for All of the Subgroups

In [56]:
import glob

all_paths = glob.glob('.cache/simulation_12_02/subgroup_*9b5933c4ae9923af*.npz')
print(len(all_paths))

2048


In [57]:
print(include_idxs)

[39 17 22 46  1 52 23 26  9 14  4  3 29 48 50 18 40  2 15 49]


In [62]:
for path in all_paths:

    
    simulation_temp = np.load(path)
    # winners_temp = np.array([change_of_basis[w] for w in simulation_temp['winners']])
    # losers_temp = np.array([change_of_basis[l] for l in simulation_temp['losers']])

    filtered_idxs_temp = np.array([i for i in range(len(simulation_temp['winners'])) if simulation_temp['winners'][i] in include_idxs and simulation_temp['losers'][i] in include_idxs])

    if len(filtered_idxs_temp) > 0:
        print('\n\nsimulation:', path)

        winners_temp = simulation_temp['winners'][filtered_idxs_temp]
        losers_temp = simulation_temp['losers'][filtered_idxs_temp]

        print('length of winners_temp:', len(winners_temp))
        print('length of losers_temp:', len(losers_temp))

        print('population misspecification_error:', ut.misspecification_error(winners_temp, losers_temp, avg_utils, beta=0.5))
        print('subgroup misspecification_error:', ut.misspecification_error(winners_temp, losers_temp, simulation_temp['r_hat'], beta=0.5))



simulation: .cache/simulation_12_02/subgroup_9b5933c4ae9923af_all_10110001000.npz
length of winners_temp: 1
length of losers_temp: 1
population misspecification_error: 0.6772584936133279
subgroup misspecification_error: 0.5375538362007142


simulation: .cache/simulation_12_02/subgroup_9b5933c4ae9923af_all_00000010100.npz
length of winners_temp: 2
length of losers_temp: 2
population misspecification_error: 1.3608859169708036
subgroup misspecification_error: 1.259396813971145


simulation: .cache/simulation_12_02/subgroup_9b5933c4ae9923af_all_00001000000.npz
length of winners_temp: 258
length of losers_temp: 258
population misspecification_error: 51.03477247176803
subgroup misspecification_error: 50.50755870037327


simulation: .cache/simulation_12_02/subgroup_9b5933c4ae9923af_all_10111001000.npz
length of winners_temp: 1
length of losers_temp: 1
population misspecification_error: 0.6839555946940071
subgroup misspecification_error: 0.47407698415197624


simulation: .cache/simulation_12

In [59]:
filtered_idxs_temp

array([], dtype=float64)

In [63]:
train_data

Dataset({
    features: ['id', 'model_a', 'model_b', 'winner', 'evaluation_session_id', 'evaluation_order', 'conversation_a', 'conversation_b', 'full_conversation', 'conv_metadata', 'category_tag', 'language', 'is_code', 'timestamp'],
    num_rows: 135634
})